# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:
  encoders:
    AppBundle\Entity\User: sha1
  role_hierarchy:
    ROLE_ADMIN: [ROLE_USER]
  providers:
    user_provider:
      entity: { class: AppBundle\Entity\User, property: username }
  firewalls:
      dev:
          pattern: ^/(_(profiler|wdt)|css|images|js)/
          security: false
      site:
          pattern: ^/
          security: true
          anonymous: true
          provider: user_provider
          form_login:
            login_path: site_security_login
            check_path: site_security_login_check
            username_parameter: login[username]
            password_parameter: login[password]
            target_path_parameter: login[targetpath]
            default_target_path: admin_homepage
            remember_me: true
          remember_me:
            key: "%secret%"
            lifetime: 86400
            path: /
            remember_me_parameter: login[rememberme]
          logout:
            path: site_security_logout
            target: site_security_login
  access_control:
    - { path: ^/admin/login$, roles: [IS_AUTHENTICATED_ANONYMOUSLY] }
    - { path: ^/admin/registration$, roles: [IS_AUTHENTICATED_ANONYMOUSLY] }
    - { path: ^/admin/remindpassword$, roles: [IS_AUTHENTICATED_ANONYMOUSLY] }
    - { path: ^/admin/remindpasswordok$, roles: [IS_AUTHENTICATED_ANONYMOUSLY] }
    - { path: ^/admin, roles: [ROLE_USER] }
    - { path: ^/, roles: [IS_AUTHENTICATED_ANONYMOUSLY] }


